# Generated by Django 5.0.3 on 2024-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0002_rename_fotogtrafia_fotografia"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("NEBULOSA", "Nebulosa"),
                    ("ESTRELA", "Estrela"),
                    ("GALAXIA", "Galáxia"),
                    ("PLANETA", "Planeta"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
