# Generated by Django 4.2.11 on 2024-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0007_fotografia_usuario_alter_fotografia_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
